### ISSUE TITLE
Tracking issues for improve the scheduling subsystem of Asterinas

### ISSUE THREAD

**Issue by tatetian** [tatetian/asterinas#1]
This issue tracks planned improvements for the scheduling subsystem of Asterinas.

- [ ] [Add the atomic mode](https://github.com/asterinas/asterinas/pull/723)
- [ ] [Deliver POSIX signals for busy-loop user code](https://github.com/asterinas/asterinas/issues/774)
- [ ] Schedule user programs preemptively
- [ ] Overhaul the scheduler API of the Framework
- [ ] Add the CFS scheduler
